name = "serverless_ai_gateway"
main = "src/index.ts"
compatibility_date = "2025-01-19"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "test-sutando"
database_id = "18a3d248-e4c8-481b-8f1d-2bff94a8b356"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1